初步完成installer-k工具开发
FeixiDev/vsdsinstaller-k pull request #1
Opened 2023-11-17 08:09 UTC by TonyLu12138

2023-11-22 02:38 UTC, mattie-feng requested changes

2023-11-22 02:38 UTC, mattie-feng commented on replacement_installation.py
> +class Re_In_:
注意一下类的命名

2023-11-23 09:06 UTC, mattie-feng commented on replacement_installation.py
> +class Replacement_Installation:
Replacement_Installation => ReplacementInstallation

2023-11-23 09:12 UTC, TonyLu12138 commented on replacement_installation.py
> +class Replacement_Installation:
OK，已修改

2023-12-05 08:38 UTC, merged